packages:
  # all packages in direct subdirs of packages/
  - "packages/*"

catalog:
  "@rslib/core": 0.13.2
  "@rstest/core": 0.3.4
  "@types/node": 22.18.1
  "typescript": 5.9.2
  "@biomejs/biome": 2.2.4
